name: Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      HTTP_BASIC_AUTH: ${{ secrets.HTTP_BASIC_AUTH }}
      ELCA_LEGACY_DATABASE_URL: http://foo.testing.com # ${{ secrets.ELCA_LEGACY_DATABASE_URL }}
      DATABASE_POOL_MAX_CONN: 2
      DATABASE_POOL_TIMEOUT: 20000
      LEGACY_DATABASE_POOL_MAX_CONN: 2
      LEGACY_DATABASE_POOL_TIMEOUT: 20000
      NEXTAUTH_URL: http://localhost:3000
      DOPPIO_API_KEY: FOO_TESTING # ${{ secrets.DOPPIO_API_KEY }}
      NEXTAUTH_SECRET: FOO_TESTING # ${{ secrets.NEXTAUTH_SECRET }}
      NEXT_PUBLIC_PASSPORT_BASE_URL: http://foo.testing.com # ${{ vars.NEXT_PUBLIC_PASSPORT_BASE_URL }}
      S3_BUCKET_NAME: elca-grp-dev
      S3_ACCESS_KEY: DUMMY_ACCESS_KEY
      S3_SECRET_KEY: DUMMY_SECRET_KEY
      S3_REGION: eu-central-3
      S3_ENDPOINT: s3.eu-central-3.ionoscloud.com
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint check
        run: yarn lint
      - name: Format check
        run: yarn prettier
      - name: Generate Prisma Clients
        run: yarn prisma:generate
      - name: Unit & Integration tests
        run: yarn test