name: Playwright Tests
on:
  push:
    branches:
      - main
      - feat-e2e-tests # TODO: remove before merging
  pull_request:
  workflow_dispatch:

jobs:
  test:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      HTTP_BASIC_AUTH: ${{ secrets.HTTP_BASIC_AUTH }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "NODE_VERSION=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn e2e:headless
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

